cc_test(
  name = "Vector_test",
  size = "small",
  srcs = ["Vector_test.cc"],
  deps = ["@com_google_googletest//:gtest_main"],
)
cc_test(
  name = "Matrix_test",
  size = "small",
  srcs = ["Matrix_test.cc"],
  deps = ["@com_google_googletest//:gtest_main"],
)
cc_test(
  name = "Quater_test",
  size = "small",
  srcs = ["Quater_test.cc"],
  deps = ["@com_google_googletest//:gtest_main"],
)